// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpdobnwsoknmvlleqisn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZG9ibndzb2tubXZsbGVxaXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTQxNDUsImV4cCI6MjA3MDc3MDE0NX0.WNf0gZUywDu2-Ahl7aA-C2ktu4XPiWMXcOE7YF00gxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});